name: Release

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Release type"
        required: true
        default: "release"
        type: choice
        options:
          - release
          - foss
          - both

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Get Version
        run: |
          VERSION=$(grep 'versionName =' app/build.gradle.kts | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@07ab29fd4a977ae4d2b275087cf67563dfdf0295
        with:
          workflow: build.yml
          name: kikyo.*
          name_is_regexp: true
          merge_multiple: true

      - name: Collect release files
        run: |
          set -e
          FILES=""

          if [[ "${{ github.event.inputs.build_type }}" != "foss" ]]; then
            FILES="$FILES kikyo-$VERSION.apk"
            FILES="$FILES kikyo-arm64-v8a-$VERSION.apk"
            FILES="$FILES kikyo-armeabi-v7a-$VERSION.apk"
            FILES="$FILES kikyo-x86-$VERSION.apk"
            FILES="$FILES kikyo-x86_64-$VERSION.apk"
          fi

          if [[ "${{ github.event.inputs.build_type }}" != "release" ]]; then
            FILES="$FILES kikyo-$VERSION-foss.apk"
          fi

          echo "RELEASE_FILES=$FILES" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        with:
          tag_name: v${{ env.VERSION }}
          name: Kikyo v${{ env.VERSION }}
          body: |
            Check out the [past release notes](https://github.com/achyutbadyal/kikyo/releases) if you're upgrading from an earlier version.

            > [!TIP]
            >
            > If you are unsure which version to download, go with  
            > `kikyo-${{ env.VERSION }}.apk`
          files: ${{ env.RELEASE_FILES }}
          draft: true
          prerelease: false
          token: ${{ secrets.MIHON_BOT_TOKEN }}